project_name: dvom

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: dvom
    main: ./cmd/dvom
    binary: dvom
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X dvom/pkg/version.Version={{.Version}}
      - -X dvom/pkg/version.GitCommit={{.Commit}}
      - -X dvom/pkg/version.BuildDate={{.Date}}

archives:
  - id: dvom
    builds:
      - dvom
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: ypeckstadt
    name: dvom
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## DVOM {{ .Tag }} Release

    DVOM - Release a new version of your project with ease.

  footer: |
    ## Installation

    ### Binary Installation
    Download the appropriate binary for your platform from the assets above.

    ### Go Install
    ```bash
    go install github.com/ypeckstadt/dvom/cmd/dvom@{{ .Tag }}
    ```

brews:
  - name: dvom
    repository:
      owner: ypeckstadt
      name: homebrew-tap
      branch: main
      token: "{{ .Env.COMMITTER_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/ypeckstadt/dvom"
    description: "DVOM - Tool to create docker volume snapshots and manage them."
    license: "MIT"
    test: |
      system "#{bin}/dvom --version"
    install: |
      bin.install "dvom"

nfpms:
  - id: dvom
    package_name: dvom
    vendor: Yves Peckstadt
    homepage: https://github.com/ypeckstadt/dvom
    maintainer: Yves Peckstadt <peckstadt.yves@gmail.com>
    description: DVOM - Tool to create docker volume snapshots and manage them.
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
