name: DVOM CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  dvom-test:
    name: DVOM Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.23, 1.22]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Download DVOM dependencies
        run: go mod download

      - name: Verify DVOM dependencies
        run: go mod verify

      - name: Run go vet on DVOM
        run: go vet ./...

      - name: Run DVOM unit tests
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload DVOM coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          flags: dvom-unittests
          name: dvom-codecov

  dvom-lint:
    name: DVOM Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go for DVOM
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run golangci-lint on DVOM
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

  dvom-build:
    name: DVOM Build & Test Binary
    runs-on: ubuntu-latest
    needs: [dvom-test, dvom-lint]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go for DVOM build
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Build DVOM binary
        run: |
          make build

      - name: Test DVOM binary functionality
        run: |
          ./bin/dvom --version
          ./bin/dvom --help

  dvom-security:
    name: DVOM Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go for DVOM security scan
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run Gosec security scanner on DVOM
        uses: securego/gosec@master
        with:
          args: './...'
